[project]
name = "turbo-quant-implm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anier Velasco", email = "anier.velasco@strategicplatform.com" }
]
requires-python = ">=3.14"
dependencies = [
    "datasets>=5.0.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "polars>=1.44.1",
    "ruff>=0.16.5",
    "scipy>=1.18.1",
    "tqdm>=4.70.0",
]

[project.scripts]
turbo-quant-implm = "turbo_quant_implm:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
